# Generated by Django 4.0.4 on 2022-12-23 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_notes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_comment', models.CharField(max_length=500)),
                ('note', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.notes', verbose_name='Название товара')),
            ],
            options={
                'verbose_name': 'Коммент',
                'verbose_name_plural': 'Комменты',
            },
        ),
    ]
